feat: refactored for the needs of csquare

diff --git a/template/script.sh.erb b/template/script.sh.erb
--- a/template/script.sh.erb
+++ b/template/script.sh.erb
@@ -1,37 +1,61 @@
 #!/usr/bin/env bash
 
-# Load the required environment
-setup_env () {
-  # Additional environment which could be moved into a module
-  # Change these to suit
-  export RSTUDIO_SERVER_IMAGE="/apps/rserver-launcher-centos7.simg"
-  export SINGULARITY_BINDPATH="/etc,/media,/mnt,/opt,/srv,/usr,/var"
-  export PATH="$PATH:/usr/lib/rstudio-server/bin"
-  export SINGULARITYENV_PATH="$PATH"
-  # In Singularity 3.5.x it became necessary to explicitly pass LD_LIBRARY_PATH
-  # to the singularity process
-  export SINGULARITYENV_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
-}
-setup_env
+<%-
+  session_dir = session.staged_root
+%>
 
-#
-# Start RStudio Server
-#
+set -ex
+
+# Load the required environment
+CACHE_PATH="/opt/cache/pyxis"
+IMAGE="rocker/rstudio:4.1"
+IMAGE_DIR="$CACHE_PATH/$(dirname "$IMAGE")"
+IMAGE_FULLPATH="$CACHE_PATH/$IMAGE"
+
+# Download image
+mkdir -p $IMAGE_DIR
+if [ ! -f "$IMAGE_FULLPATH" ]; then
+	srun --ntasks=1 --mem=0 \
+		--container-image="$IMAGE" \
+		--container-save="$IMAGE_FULLPATH" \
+		true
+fi
+
+tries=1; while [ "$tries" -lt 10 ]; do
+	if file "$IMAGE_FULLPATH" | grep -q "Squashfs filesystem"; then
+		break
+	fi
+	echo "Image is not complete. Wait a few seconds... ($tries/10)"
+	sleep 10
+	tries=$((tries+1))
+done
+if [ "$tries" -ge 10 ]; then
+	echo "Image import failure. Please try an another experiment."
+	exit 1
+fi
+
+. $LMOD_PKG/init/sh
 
 # PAM auth helper used by RStudio
-export RSTUDIO_AUTH="${PWD}/bin/auth"
-
-# Generate an `rsession` wrapper script
-export RSESSION_WRAPPER_FILE="${PWD}/rsession.sh"
+export WORKING_DIR="<%= session_dir %>"
+export RSTUDIO_AUTH="$WORKING_DIR/bin/auth"
+export RSESSION_WRAPPER_FILE="$WORKING_DIR/rsession.sh"
 (
 umask 077
-sed 's/^ \{2\}//' > "${RSESSION_WRAPPER_FILE}" << EOL
+sed 's/^ \{2\}//' > "$WORKING_DIR/rsession.sh" << EOL
   #!/usr/bin/env bash
 
   # Log all output from this script
-  export RSESSION_LOG_FILE="${PWD}/rsession.log"
+  export RSESSION_LOG_FILE="$WORKING_DIR/rsession.log"
 
   exec &>>"\${RSESSION_LOG_FILE}"
+
+  # rsession.sh doesn't share the same env as the outside script, so these
+  # need to be set explicitly
+  export R_LIBS_SITE="${R_LIBS_SITE}"
+  export MODULEPATH_ROOT="$MODULEPATH_ROOT"
+  export MODULEPATH="$MODULEPATH"
+  export LMOD_PKG="$LMOD_PKG"
 
   # Launch the original command
   echo "Launching rsession..."
@@ -39,26 +63,26 @@ sed 's/^ \{2\}//' > "${RSESSION_WRAPPER_FILE}" << EOL
   exec rsession --r-libs-user "${R_LIBS_USER}" "\${@}"
 EOL
 )
-chmod 700 "${RSESSION_WRAPPER_FILE}"
+chmod 755 "$WORKING_DIR/rsession.sh"
 
 # Set working directory to home directory
 cd "${HOME}"
 
-export TMPDIR="$(mktemp -d)"
-
-mkdir -p "$TMPDIR/rstudio-server"
-python -c 'from uuid import uuid4; print(uuid4())' > "$TMPDIR/rstudio-server/secure-cookie-key"
-chmod 0600 "$TMPDIR/rstudio-server/secure-cookie-key"
-
-set -x
 # Launch the RStudio Server
 echo "Starting up rserver..."
 
-singularity run -B "$TMPDIR:/tmp" "$RSTUDIO_SERVER_IMAGE" \
- --www-port "${port}" \
- --auth-none 0 \
- --auth-pam-helper-path "${RSTUDIO_AUTH}" \
- --auth-encrypt-password 0 \
- --rsession-path "${RSESSION_WRAPPER_FILE}"
+srun --container-workdir=${HOME} \
+ --container-image="$IMAGE_FULLPATH" \
+ --no-container-remap-root \
+ --container-mount-home \
+ --container-writable \
+ --preserve-env \
+ --container-mounts="/opt/gentoo:/opt/gentoo:ro,/opt/cvmfs:/opt/cvmfs:ro,/etc/slurm/taskprolog:/etc/slurm/taskprolog:ro,$WORKING_DIR:$WORKING_DIR:ro" \
+ rserver --www-port ${port} \
+  --server-daemonize=0 \
+  --auth-none 0 \
+  --auth-pam-helper-path ${RSTUDIO_AUTH} \
+  --auth-encrypt-password 0 \
+  --rsession-path ${RSESSION_WRAPPER_FILE}
 
-echo 'Singularity as exited...'
+echo 'Server exited...'
